module.exports = {
	port: process.env.PORT,
	host: process.env.HOST,
	dbHost: process.env.DB_HOST,
	dbPort: process.env.DB_PORT,
	dbUser: process.env.DB_USER,
	dbPassword: process.env.DB_PASS,
	dbDatabase: process.env.DB_DATABASE,
	appKey: process.env.APP_KEY,
	googleClientId: process.env.GOOGLE_CLIENT_ID,
	googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
	facebookClientId: process.env.FACEBOOK_CLIENT_ID,
	facebookClientSecret: process.env.FACEBOOK_CLIENT_SECRET,
	tokenExpiresIn: '1h',
};
