version: '3.1'

services:
    db:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    app:
        image: node:14
        restart: always
        working_dir: /src
        ports:
            - 3333:3333
        volumes:
            - ./:/src
        command: npm run dev
